// Demo/synthetic catalog for the buildathon demo. Prices in INR rupees.
// `compatKey` values are resolved to real ObjectIds after insertion (see seed.js)
// so we can wire up realistic "frequently bought with" relationships.
export const productSeeds = [
  {
    key: 'gaming-mouse',
    imageUrl: `https://picsum.photos/seed/gaming-mouse/400/300`,
    name: 'Nova X Gaming Mouse',
    description: 'Lightweight wired gaming mouse with 12,000 DPI optical sensor and RGB lighting.',
    category: 'Peripherals',
    price: 1499,
    inventory: 25,
    tags: ['gaming', 'mouse', 'rgb', 'wired'],
    compatKeys: ['mouse-pad', 'mouse-grip-tape'],
    shippingInfo: 'Ships within 2 business days.',
    returnPolicy: '7-day return policy.',
  },
  {
    key: 'mouse-pad',
    imageUrl: `https://picsum.photos/seed/gaming-mouse/400/300`,
    name: 'GlideZone Extended Mouse Pad',
    description: 'Extended cloth mouse pad, 900x400mm, stitched edges for durability.',
    category: 'Peripherals',
    price: 499,
    inventory: 40,
    tags: ['gaming', 'mousepad', 'accessory'],
    compatKeys: ['gaming-mouse'],
    shippingInfo: 'Ships within 2 business days.',
    returnPolicy: '7-day return policy.',
  },
  {
    key: 'mouse-grip-tape',
    imageUrl: `https://picsum.photos/seed/gaming-mouse/400/300`,
    name: 'ProGrip Mouse Grip Tape',
    
    description: 'Anti-slip grip tape kit, precut for most gaming mice.',
    category: 'Peripherals',
    price: 299,
    inventory: 60,
    tags: ['gaming', 'mouse', 'accessory'],
    compatKeys: ['gaming-mouse'],
    shippingInfo: 'Ships within 2 business days.',
    returnPolicy: '7-day return policy.',
  },
  {
    key: 'running-shoe',
    imageUrl: `https://picsum.photos/seed/gaming-mouse/400/300`,
    name: 'AeroStride Running Shoes',
    description: 'Breathable mesh running shoes built for daily jogging, cushioned sole.',
    category: 'Footwear',
    price: 2199,
    inventory: 18,
    tags: ['running', 'shoes', 'jogging', 'daily-wear'],
    compatKeys: ['running-socks', 'insoles'],
    shippingInfo: 'Ships within 3 business days.',
    returnPolicy: '15-day return policy.',
  },
  {
    key: 'running-socks',
    imageUrl: `https://picsum.photos/seed/gaming-mouse/400/300`,
    name: 'TrailFlex Running Socks (Pack of 3)',
    description: 'Moisture-wicking cushioned running socks, arch support.',
    category: 'Footwear',
    price: 399,
    inventory: 2, // deliberately low — demonstrates low-inventory approval rule
    tags: ['running', 'socks', 'accessory'],
    compatKeys: ['running-shoe'],
    shippingInfo: 'Ships within 3 business days.',
    returnPolicy: '15-day return policy.',
  },
  {
    key: 'insoles',
    imageUrl: `https://picsum.photos/seed/gaming-mouse/400/300`,
    name: 'ComfortStep Cushioned Insoles',
    description: 'Gel cushioned insoles for extra shock absorption during long runs.',
    category: 'Footwear',
    price: 349,
    inventory: 30,
    tags: ['running', 'insoles', 'accessory'],
    compatKeys: ['running-shoe'],
    shippingInfo: 'Ships within 3 business days.',
    returnPolicy: '15-day return policy.',
  },
  {
    key: 'laptop-bag',
    imageUrl: `https://picsum.photos/seed/gaming-mouse/400/300`,
    name: 'UrbanCarry 15" Laptop Bag',
    description: 'Water-resistant laptop backpack with padded compartment, fits up to 15.6".',
    category: 'Bags',
    price: 1899,
    inventory: 15,
    tags: ['laptop', 'bag', 'backpack', 'travel'],
    compatKeys: ['laptop-sleeve'],
    shippingInfo: 'Ships within 2 business days.',
    returnPolicy: '7-day return policy.',
  },
  {
    key: 'laptop-sleeve',
    imageUrl: `https://picsum.photos/seed/gaming-mouse/400/300`,
    name: 'SoftShell Laptop Sleeve 15"',
    description: 'Neoprene protective sleeve, fits inside most laptop bags.',
    category: 'Bags',
    price: 449,
    inventory: 22,
    tags: ['laptop', 'sleeve', 'accessory'],
    compatKeys: ['laptop-bag'],
    shippingInfo: 'Ships within 2 business days.',
    returnPolicy: '7-day return policy.',
  },
  {
    key: 'mechanical-keyboard',
    imageUrl: `https://picsum.photos/seed/gaming-mouse/400/300`,
    name: 'KeyForge TKL Mechanical Keyboard',
    description: 'Tenkeyless mechanical keyboard with hot-swappable switches.',
    category: 'Peripherals',
    price: 3499,
    inventory: 10,
    tags: ['gaming', 'keyboard', 'mechanical'],
    compatKeys: ['wrist-rest'],
    shippingInfo: 'Ships within 2 business days.',
    returnPolicy: '7-day return policy.',
  },
  {
    key: 'wrist-rest',
    imageUrl: `https://picsum.photos/seed/gaming-mouse/400/300`,
    name: 'RestEase Keyboard Wrist Rest',
    description: 'Memory foam wrist rest for extended typing sessions.',
    category: 'Peripherals',
    price: 349,
    inventory: 35,
    tags: ['keyboard', 'accessory', 'ergonomic'],
    compatKeys: ['mechanical-keyboard'],
    shippingInfo: 'Ships within 2 business days.',
    returnPolicy: '7-day return policy.',
  },
];
